# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1410697704);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1410697824);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1410710724);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1410697584);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.blocked", "{\"6sDppVK2/q4F0F+XjGzAVA==\":1,\"c8UurIXhjQ11dyRTKcfquA==\":1,\"LFETK7YLxxOQHAlGw/7R2g==\":1,\"DKPwuNR9RAwayGpYjz4VFw==\":1,\"VKU5qhxXIkqZ5axnyYoDXg==\":1,\"chLU5hwaPWGO4BqIq2W8dg==\":1,\"WlFPqq6bUL6N4rHvLH3STw==\":1,\"/0+U6Kvm1/dI8Y5JD/vnSw==\":1,\"B75iCDeDJItD+BxtLgX+Nw==\":1,\"ncgIotJC0dx8gyYS1YAyWw==\":1,\"/cdBgbA8uAXcUP/uLYQo2A==\":1,\"3HqKMPU2jDH5YEMkjTILiw==\":1,\"DNdNZMKNriMNOjwWLEn9OQ==\":1,\"jSQp8BEmzK4q8vpJmO/y8g==\":1,\"eEUxGyEzL2r9pqUbz1TQyA==\":1,\"kWlsyaEGWSvzmDnvJVhIQQ==\":1,\"a82GBN3QPkMQodwcdAlu/w==\":1,\"O/KLiq/i0tH2hxbIdSFe/w==\":1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.slowStartup.averageTime", 2115);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20140722223050");
user_pref("browser.startup.homepage_override.mstone", "24.7.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1410783863558");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1410697463558");
user_pref("datareporting.sessions.current.activeTicks", 12);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 861);
user_pref("datareporting.sessions.current.main", 61);
user_pref("datareporting.sessions.current.sessionRestored", 905);
user_pref("datareporting.sessions.current.startTime", "1410703403954");
user_pref("datareporting.sessions.current.totalTime", 8686);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1410697461132,\"a\":135,\"t\":967,\"c\":true,\"m\":1456,\"fp\":3997,\"sr\":4059}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1410703384835,\"a\":3,\"t\":12,\"c\":true,\"m\":61,\"fp\":1211,\"sr\":1258}");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.7.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1409783465000,\"rdfTime\":1406072653000}}}]");
user_pref("extensions.lastAppVersion", "24.7.0");
user_pref("extensions.lastPlatformVersion", "24.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140722223050");
user_pref("gecko.mstone", "24.7.0");
user_pref("idle.lastDailyNotification", 1410703719);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1410703719);
user_pref("places.history.expiration.transient_current_max_pages", 48308);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1410703719);
user_pref("toolkit.startup.last_success", 1410703404);
user_pref("toolkit.telemetry.previousBuildID", "20140722223050");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1413289467);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
